### ISSUE TITLE
Unknown field type "chained-select"

### ISSUE THREAD

**Issue by matepaiva** [iamntz/carbon-chained-select#1]
Hello, first of all, thanks for open sourcing your work.

I am trying to use this package, but all I get is "Unknown field type 'chained-select'" from Wordpress.

I have already installed other packages that add custom Carbon Field types, such as type "number" (https://github.com/htmlburger/carbon-field-number) and it worked successfully, but with your package, I can't make it work. Maybe I am making something wrong during the installation?

What I did:

1. Added `"iamntz/carbon-chained-select": "dev-master"` to my `require` list in the `composer.json` of my theme;
2. `Composer update` installed the package successfully;
3. Created a field using that field type:

```
Field::make('chained-select', 'chained_select', __('chained-select', 'app'))
	->add_options([
		'__label__' => 'Select 1', // field label

		'value1' => 'Option Text 1',
		'value2' => 'Option Text 2',

		'value3_nested' => [
			'__label__' => 'Select 2 (nested)', // option text AND next field label

			'select-2-1-1' => 'Option text 2 - 1',
			'select-2-1-2' => 'Option text 2 - 2',
		],
	]),
```

Maybe I need to bootstrap the package with some code before using it?

Thanks in advance!

**Comment by iamntz** [comment]
Hey @matepaiva , please note that this plugin only works with Carbon 2, is not compatible with Carbon 3 yet. 

Can you confirm your version please?

**Comment by matepaiva** [comment]
Yep, that is the problem. Do you have any tips about an alternative using Carbon 3?

**Comment by iamntz** [comment]
Unfortunately no. V3 changed a LOT of the API, which means that `chained select` needs to be basically re-written from scratch. Maybe this will happen in the future :)

**Comment by matepaiva** [comment]
Ok, thanks for the information. If you could, it would be nice to have a warning in the README. I found this package because of another developer who was struggling with the installation as well. :)

**Comment by iamntz** [comment]
Hey @matepaiva, i've managed to rewrite the whole damn thing! I think you could try it now ;)
